### ISSUE TITLE
Проверка проекта на валидность

### ISSUE THREAD

**Issue by A9FM** [samplec0de/eljur-bot#2]
Данный проект еще работает? Не изменился ли API эл. жура? Думаю форк написать под нужды знакомого.
Также хотелось бы узнать, куда вставлять Token телеграм бота? Ни конфига, ничего... не удобно это

**Comment by samplec0de** [comment]
Привет! Пациент скорее мертв, чем жив, к сожалению. На этом проекте я учился питону по большому счету, да и не только ему, так что да, далеко не идеально.

**Comment by samplec0de** [comment]
для передачи токена используется переменная окружения token

**Comment by samplec0de** [comment]
еще надо поднять монгу и дать коннект строку к ней https://github.com/samplec0de/eljur-bot/blob/master/eljurbot.py#L47

**Comment by samplec0de** [comment]
и указать имя бд https://github.com/samplec0de/eljur-bot/blob/master/eljurbot.py#L48

**Comment by samplec0de** [comment]
бот, к слову, умер, не может ИД сообщения получить от апи, что-то поменяли

**Comment by A9FM** [comment]
Очень жаль
